server:
  port: 8181

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false\
    &serverTimezone=GMT%2B8"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WF##(5B9rK5OVZhNGs0fsZiJv8/dfzGHLH4FQpOEg2flAKn+BYcOHdDWyx1qi+dK9L/di)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jasypt:
  encryptor:
    bean: wfEncryptorBean
    property:
      prefix: WF##(
      suffix: )

wf:
  hello:
    prefix: Hello
    suffix: Master
